name: deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: agile-anagram-469914-e2
      GCP_REGION: asia-southeast1
      CLOUD_RUN_SERVICE: edenos-mcp-bridge
      ARTIFACT_REPO: containers
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - uses: docker/setup-buildx-action@v3
      - uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom-spdx.json
      - name: Build + Push
        run: |
          export TAG="${GITHUB_SHA::7}"
          ./scripts/deploy.sh
